name: k3s-on-host

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-package-feature:
        runs-on: ubuntu-latest
    
        permissions:
            contents: read
            packages: write
    
        steps:
        - uses: actions/checkout@v2

            
        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@km/add_structure
          with:
            env_file: ./env/spacefx.env
            token: ${{ secrets.GITHUB_TOKEN }}

        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-oras@km/add_structure
          with:
            oras_version: 0.16.0

        - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-devcontainer-cli@km/add_structure

        - name: Building Feature Package
          run: |
            mkdir -p ./output

            echo "devcontainer features package --force-clean-output-folder ./.devcontainer/features --output-folder ./output"
            devcontainer features package --force-clean-output-folder ./.devcontainer/features --output-folder ./output
            sub_exit_code=${PIPESTATUS[0]}
            if [[ $sub_exit_code -gt 0 ]]; then
                echo "Previous step failed.  Troubleshoot"
                exit 1
            fi

        - name: Pushing Feature Package
          run: |
            echo "oras push ${{ env.REGISTRY }}/microsoft/devcontainers/features/k3s-on-host:latest --config /dev/null:application/vnd.devcontainers ./output/devcontainer-feature-k3s-on-host.tgz:application/vnd.devcontainers.layer.v1+tar"
            oras push ${{ env.REGISTRY }}/microsoft/devcontainers/features/k3s-on-host:latest \
              --config /dev/null:application/vnd.devcontainers \
                      ./output/devcontainer-feature-k3s-on-host.tgz:application/vnd.devcontainers.layer.v1+tar
            sub_exit_code=${PIPESTATUS[0]}
            if [[ $sub_exit_code -gt 0 ]]; then
                echo "Previous step failed.  Troubleshoot"
                exit 1
            fi
      
            echo "oras push ${{ env.REGISTRY }}/microsoft/devcontainers/features/k3s-on-host:latest --config /dev/null:application/vnd.devcontainers ./output/devcontainer-feature-k3s-on-host.tgz:application/vnd.devcontainers.collection.layer.v1+json"
            oras push ${{ env.REGISTRY }}/microsoft/devcontainers/features/k3s-on-host:latest \
              --config /dev/null:application/vnd.devcontainers \
                      ./output/devcontainer-feature-k3s-on-host.tgz:application/vnd.devcontainers.collection.layer.v1+json
            sub_exit_code=${PIPESTATUS[0]}
            if [[ $sub_exit_code -gt 0 ]]; then
                echo "Previous step failed.  Troubleshoot"
                exit 1
            fi
